// Modules : every file is a module in CommonJS. a module is encapsulated code
const names = require('./4-names')
const sayHi = require('./5-utils')
const data = require('./6-alternative-flavour')
require('./7-mind-grenade')
require('./5-utils')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)
console.log(names)